# The Python Programming Language : Functions

In [51]:
x = 1
y = 2
x+y

3

In [52]:
x

1

In [53]:
def add_numbers(x,y):
    return x+y
add_numbers(1,2)

3

In [54]:
def add_numbers(x,y,z=None):
    if(z==None):
        return x+y
    else:
        return x+y+z
print(add_numbers(1,2))
print(add_numbers(1,2,3))

3
6


# The Python Programming Language :Python types and Sequence

In [55]:
type('this is a string')

str

In [56]:
type(None)

NoneType

In [57]:
type(1.0)

float

In [58]:
type(1)

int

In [59]:
type(add_numbers)

function

### Tuples
Sequence of variable which is immutable. It has items in ordering that cannot be changed once created.

In [60]:
x = (1,'a',2,'b')
type(x)

tuple

### List
These are similar to tuple, but they can be mutable, so you can change the length, number of elements and their element values.

In [61]:
x = [1,'a',2,'b']
type(x)

list

We can change the content of the list using:
    
1. append()

In [62]:
x.append(100)
print(x)

[1, 'a', 2, 'b', 100]


In [63]:
for item in x:
    print(item)

1
a
2
b
100


In [64]:
i =0
while(i!= len(x)):
    print(x[i])
    i+=1

1
a
2
b
100


In [65]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [66]:
[1]*3

[1, 1, 1]

In [67]:
1 in [1,2,3]

True

### Strings

In [68]:
X = 'This is a string'
print(X[0])
print(X[0:1])
print(X[0:2])

T
T
Th


In [69]:
X[-1]

'g'

In [70]:
X[-4:-2]

'ri'

In [71]:
X[:3]

'Thi'

In [72]:
X[3:]

's is a string'

In [73]:
firstname ='Tanwir'
lastname ='Khan'
print(firstname + ' ' + lastname)
print(firstname * 3)
print('Tanwir' in firstname) 

Tanwir Khan
TanwirTanwirTanwir
True


In [74]:
firstname = 'Christopher Arthur Hasen Brooks'.split(' ')[0]
lastname = 'Christopher Arthur Hasen Brooks'.split(' ')[-1]
print(firstname)
print(lastname)

Christopher
Brooks


In [75]:
'Tanwir' + 2

TypeError: can only concatenate str (not "int") to str

In [76]:
'Tanwir' + str(2)

'Tanwir2'

### Dictionary

In [77]:
X = {'tanwir Khan':'tkhan.vrf@hng.com', 'Chris Moss':'chrismoss@ghamil.com'}
X['tanwir Khan']

'tkhan.vrf@hng.com'

In [78]:
X['Christopher Arthur'] = None
X['Christopher Arthur']

In [79]:
#### Iterating over the keys in a dictionary and extracting the values
for name in X:
    print(X[name])

tkhan.vrf@hng.com
chrismoss@ghamil.com
None


In [80]:
## Iterating over the values

for i in X.values():
    print(i)

tkhan.vrf@hng.com
chrismoss@ghamil.com
None


In [81]:
## iterating over both the values and the keys

for name, email in X.items():
    print("Key: ", name)
    print("Values: ",email)

Key:  tanwir Khan
Values:  tkhan.vrf@hng.com
Key:  Chris Moss
Values:  chrismoss@ghamil.com
Key:  Christopher Arthur
Values:  None


### Unpacking

In [82]:
X = ('Tanwir','Khan','tkhagyh@hgnd.com')

In [83]:
fname, lname, email = X

In [84]:
fname

'Tanwir'

In [85]:
y = ('Tanwir','Khan','9898897878','gthgh.jkki@hnhj.com')

In [86]:
Fname, Lname, Phone_no = y

ValueError: too many values to unpack (expected 3)

# Python More on strings

In [87]:
sales_record = {'price':3.24,
               'num_items':4,
               'person':'Chris'}
sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'
print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['price']*sales_record['num_items']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


# Python Demonstration: Reading and Writing CSV files

In [88]:
import csv
%precision 2
with open('C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/mpg.csv')as csvfile:
    mpg = list(csv.DictReader(csvfile))
mpg[:3]

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [89]:
len(mpg)

234

In [90]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [91]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [92]:
sum(float(d['hwy']) for d in mpg)/ len(mpg)

23.44

In [93]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [94]:
total = []
for i in cylinders:
    count = 0
    sumtotal = 0
    for j in mpg:
        if j['cyl'] == i:
            sumtotal+= float(j['cty'])
            count+=1
    total.append((i, sumtotal/count))
total.sort(key = lambda x:x[0])
total

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [95]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [96]:
total = []
for i in vehicleclass:
    sumtotal = 0
    count = 0
    for j in mpg:
        if j['class']==i:
            sumtotal+= float(j['hwy'])
            count+=1
    total.append((i, sumtotal/count))
total.sort(key = lambda x:x[1])
total

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

# The Python Programming language: Date and Time

In [97]:
import datetime as dt
import time as tm

In [98]:
tm.time()

1623448086.71

In [99]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2021, 6, 11, 17, 48, 6, 721571)

In [100]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2021, 6, 11, 17, 48, 6)

In [101]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(days=100)

In [102]:
today = dt.date.today()
today

datetime.date(2021, 6, 11)

In [103]:
today- delta

datetime.date(2021, 3, 3)

In [104]:
today > today - delta

True

# Advanced Python Objects, map()

In [105]:
store1 = [10.0,11.0,12.34,2.34]
store2 = [9.0, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [106]:
print(list(cheapest))

[9.0, 11.0, 12.34, 2.01]


# Advanced Python Lambda and List Comprehensions

In [107]:
my_function = lambda a,b,c: a+b-c

In [108]:
my_function(1,2,3)

0

In [109]:
my_list = []
for i in range(1,10):
    if i%2 == 0:
        my_list.append(i)
my_list

[2, 4, 6, 8]

In [110]:
my_list = [number for number in range(1,10) if number%2 == 0]
my_list

[2, 4, 6, 8]

# Numerical Python Library (NumPy)

In [111]:
import numpy as np
import math

## Array Creation

In [112]:
# Arrays are displayed as a list or list of lists and can be created through list as well. When creating an
# array, we pass in a list as an argument in numpy array.

a = np.array([1,2,3])
print(a)

# We can print the number of dimensions of a list using the ndim attribute

print(a.ndim)

[1 2 3]
1


In [113]:
# If we pass in a list of lists in numpy array, we create a multi-dimensional array, for instance, a matrix

b = np.array([[2,12,13],[1,24,11]])
b

array([[ 2, 12, 13],
       [ 1, 24, 11]])

In [114]:
# We can print out the length of each dimension by calling the shape attribute, which returns a tuple
b.shape

(2, 3)

In [115]:
# We can also check the type of items in the array

a.dtype

dtype('int32')

In [116]:
# Besides integers, floats are also accepted in numpy arrays

c = np.array([1.2,3.32,21.3])
c.dtype.name

'float64'

In [117]:
# Let's look at the data in our array

c

array([ 1.2 ,  3.32, 21.3 ])

In [118]:
# Note that numpy automatically converts integers, like 5, up to floats, since there is no loss of prescision.
# Numpy will try and give you the best data type format possible to keep your data types homogeneous, which
# means all the same, in the array

In [119]:
# Sometimes we know the shape of an array that we want to create, but not what we want to be in it. numpy
# offers several functions to create arrays with initial placeholders, such as zero's or one's.
# Lets create two arrays, both the same shape but with different filler values

a = np.ones((2,3))
print(a)

b = np.zeros((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [120]:
# We can also generate an array with random numbers

c = np.random.rand(2,3)
print(c)

[[0.17681069 0.68118242 0.68233368]
 [0.83461455 0.25908308 0.84409974]]


In [121]:
# You'll see zeros, ones, and rand used quite often to create example arrays, especially in stack overflow
# posts and other forums.

In [122]:
# We can also create a sequence of numbers in an array with the arrange() function. The fist argument is the
# starting bound and the second argument is the ending bound, and the third argument is the difference between
# each consecutive numbers

# Let's create an array of every even number from ten (inclusive) to fifty (exclusive)

f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [123]:
# if we want to generate a sequence of floats, we can use the linspace() function. In this function the third
# argument isn't the difference between two numbers, but the total number of items you want to generate.
np.linspace(0,2,15)# 15 numbers from 0 (inclusive) to 2 (inclusive)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Array Operations

In [124]:
# We can do many things on arrays, such as mathematical manipulation (addition, subtraction, square,
# exponents) as well as use boolean arrays, which are binary values. We can also do matrix manipulation such
# as product, transpose, inverse, and so forth.

In [125]:
# Arithmetic operators on array apply elementwise.

# Let's create a couple of arrays
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a-b
c
# And let's look at a times b
d = a*b
d

array([ 10,  40,  90, 160])

In [126]:
# With arithmetic manipulation, we can convert current data to the way we want it to be. Here's a real-world
# problem I face - I moved down to the United States about 6 years ago from Canada. In Canada we use celcius
# for temperatures, and my wife still hasn't converted to the US system which uses farenheit. With numpy I 
# could easily convert a number of farenheit values, say the weather forecase, to ceclius

# Let's create an array of typical Ann Arbor winter farenheit values

farehneit = np.array([0,-10, -5, -15, 0])

# And the formula for conversion is ((°F − 32) × 5/9 = °C)

celcius = (farehneit - 33) * (5/9)
celcius

array([-18.33333333, -23.88888889, -21.11111111, -26.66666667,
       -18.33333333])

In [127]:
# Another useful and important manipulation is the boolean array. We can apply an operator on an array, and a
# boolean array will be returned for any element in the original, with True being emitted if it meets the condition and False oetherwise.
# For instance, if we want to get a boolean array to check celcius degrees that are greater than -20 degrees

celcius > -20

array([ True, False, False, False,  True])

In [128]:
# Here's another example, we could use the modulus operator to check numbers in an array to see if they are even. 
# Recall that modulus does division but throws away everything but the remainder (decimal) portion)

celcius%2 ==0

array([False, False, False, False, False])

In [129]:
# Besides elementwise manipulation, it is important to know that numpy supports matrix manipulation. Let's
# look at matrix product. if we want to do elementwise product, we use the "*" sign

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A*B

array([[ 5, 12],
       [21, 32]])

In [130]:
# if we want to do matrix product, we use the "@" sign or use the dot function

A@B

array([[19, 22],
       [43, 50]])

In [131]:
# A few more linear algebra concepts are worth layering in here. You might recall that the product of two
# matrices is only plausible when the inner dimensions of the two matrices are the same. The dimensions refer
# to the number of elements both horizontally and vertically in the rendered matricies you've seen here. We
# can use numpy to quickly see the shape of a matrix:

A.shape

(2, 2)

In [132]:
# When manipulating arrays of different types, the type of the resulting array will correspond to 
# the more general of the two types. This is called upcasting.

# Let's create an array of integers

array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1.dtype)

array2 = np.array([[1.1,2.2,3.5,8.9],[4.5,7.7,2.3,44.1]])
print(array2.dtype)

int32
float64


In [133]:
# Integers (int) are whole numbers only, and Floating point numbers (float) can have a whole number portion
# and a decimal portion. The 64 in this example refers to the number of bits that the operating system is
# reserving to represent the number, which determines the size (or precision) of the numbers that can be
# represented.

In [134]:
# Let's do an addition for the two arrays

array3 = array1+array2
print(array3)

[[ 2.1  4.2  6.5 12.9]
 [ 9.5 13.7  9.3 52.1]]


In [135]:
# Notice how the items in the resulting array have been upcast into floating point numbers

In [136]:
# Numpy arrays have many interesting aggregation functions on them, such as  sum(), max(), min(), and mean()
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

110.30000000000001
52.1
2.1
13.787500000000001


In [137]:
# For two dimensional arrays, we can do the same thing for each row or column
# let's create an array with 15 elements, ranging from 1 to 15, 
# with a dimension of 3X5

b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [138]:
# Now, we often think about two dimensional arrays being made up of rows and columns, but you can also think
# of these arrays as just a giant ordered list of numbers, and the *shape* of the array, the number of rows
# and columns, is just an abstraction that we have for a particular purpose. Actually, this is exactly how
# basic images are stored in computer environments.

# Let's take a look at an example and see how numpy comes into play.

In [25]:
# For this demonstration I'll use the python imaging library (PIL) and a function to display images in the
# Jupyter notebook

import cv2
import matplotlib.pyplot as plt

image = cv2.imread('C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/mouse.jpg')

cv2.imshow("A",image)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows()

In [26]:
# Now, we can conver this image to a numpy array

import numpy as np
array = np.array(image)
print(array.shape)
array

(471, 640, 3)


array([[[ 92, 112, 143],
        [ 92, 112, 143],
        [ 92, 112, 143],
        ...,
        [ 74,  94, 125],
        [ 74,  94, 125],
        [ 74,  94, 125]],

       [[ 93, 113, 144],
        [ 93, 113, 144],
        [ 93, 113, 144],
        ...,
        [ 73,  93, 124],
        [ 73,  93, 124],
        [ 73,  93, 124]],

       [[ 94, 114, 145],
        [ 94, 114, 145],
        [ 94, 114, 145],
        ...,
        [ 73,  93, 124],
        [ 73,  93, 124],
        [ 73,  93, 124]],

       ...,

       [[ 54, 100, 147],
        [ 53,  99, 146],
        [ 50,  97, 149],
        ...,
        [ 62, 120, 155],
        [ 59, 116, 148],
        [ 51, 111, 141]],

       [[ 53, 102, 148],
        [ 51, 100, 146],
        [ 47,  95, 147],
        ...,
        [ 59, 115, 150],
        [ 58, 112, 147],
        [ 53, 109, 144]],

       [[ 64, 104, 146],
        [ 63, 101, 143],
        [ 54,  94, 142],
        ...,
        [ 55, 112, 144],
        [ 56, 110, 143],
        [ 51, 108, 140]]

In [29]:
# Here we see that we have a 2304 X 3456 X 3 array and that the values are all uint8. The uint means that they are
# unsigned integers (so no negative numbers) and the 8 means 8 bits per byte. This means that each value can
# be up to 2*2*2*2*2*2*2*2=256 in size (well, actually 255, because we start at zero). For black and white
# images black is stored as 0 and white is stored as 255. So if we just wanted to invert this image we could
# use the numpy array to do so

#lets create an array of the same shape

mask = np.full(array.shape,255)
mask.shape

(471, 640, 3)

In [30]:
# Now let's subtract that from the modified array
modified_array = array - mask

# And lets convert all of the negative values to positive values
modified_array = modified_array*(-1)

# And as a last step, let's tell numpy to set the value of the datatype correctly

modified_array = modified_array.astype(np.uint8)
modified_array

array([[[163, 143, 112],
        [163, 143, 112],
        [163, 143, 112],
        ...,
        [181, 161, 130],
        [181, 161, 130],
        [181, 161, 130]],

       [[162, 142, 111],
        [162, 142, 111],
        [162, 142, 111],
        ...,
        [182, 162, 131],
        [182, 162, 131],
        [182, 162, 131]],

       [[161, 141, 110],
        [161, 141, 110],
        [161, 141, 110],
        ...,
        [182, 162, 131],
        [182, 162, 131],
        [182, 162, 131]],

       ...,

       [[201, 155, 108],
        [202, 156, 109],
        [205, 158, 106],
        ...,
        [193, 135, 100],
        [196, 139, 107],
        [204, 144, 114]],

       [[202, 153, 107],
        [204, 155, 109],
        [208, 160, 108],
        ...,
        [196, 140, 105],
        [197, 143, 108],
        [202, 146, 111]],

       [[191, 151, 109],
        [192, 154, 112],
        [201, 161, 113],
        ...,
        [200, 143, 111],
        [199, 145, 112],
        [204, 147, 115]]

In [31]:
# And lastly, lets display this new array. 

cv2.imshow("B",modified_array)
cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows()

# Indexing, Slicing and Iterating

In [32]:
# Indexing, slicing and iterating are extremely important for data manipulation and analysis because these
# techinques allow us to select data based on conditions, and copy or update data.

## Indexing

In [33]:
# First we are going to look at integer indexing. A one-dimensional array, works in similar ways as a list -
# To get an element in a one-dimensional array, we simply use the offset index.

a = np.array([1,2,3])
a[1]

2

In [34]:
# For multidimensional array, we need to use integer array indexing, let's create a new multidimensional array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# if we want to select one certain element, we can do so by entering the index, which is comprised of two
# integers the first being the row, and the second the column

a[1,1]

5

In [37]:
# if we want to get multiple elements 
# for example, 1, 4, and 6 and put them into a one-dimensional array
# we can enter the indices directly into an array function

np.array([a[0,0],a[1,0],a[1,2]])

array([1, 4, 6])

In [40]:
# we can also do that by using another form of array indexing, which essentially "zips" the first list and the
# second list up

print(a[[0,1,1],[0,0,2]])

[1 4 6]


## Boolean Indexing

In [41]:
# Boolean indexing allows us to select arbitrary elements based on conditions. For example, in the matrix we
# just talked about we want to find elements that are greater than 5 so we set up a conditon a >5 
print(a >5)
# This returns a boolean array showing that if the value at the corresponding index is greater than 5

[[False False False]
 [False False  True]
 [ True  True  True]]


In [42]:
# We can then place this array of booleans like a mask over the original array to return a one-dimensional 
# array relating to the true values.

print(a[a>5])

[6 7 8 9]


## Slicing

In [44]:
# Slicing is a way to create a sub-array based on the original array. For one-dimensional arrays, slicing 
# works in similar ways to a list. To slice, we use the : sign. For instance, if we put :3 in the indexing
# brackets, we get elements from index 0 to index 3 (excluding index 3)

a = np.array([0,1,2,3,4,5,6,7])
print(a[:3])

[0 1 2]


In [45]:
# By putting 2:4 in the bracket, we get elements from index 2 to index 4 (excluding index 4)
print(a[2:4])

[2 3]


In [46]:
# For multi-dimensional arrays, it works similarly, lets see an example
a = np.array([[1,2,3],[4,54,6],[6,7,8]])
a

array([[ 1,  2,  3],
       [ 4, 54,  6],
       [ 6,  7,  8]])

In [47]:
# First, if we put one argument in the array, for example a[:2] then we would get all the elements from the 
# first (0th) and second row (1th)

a[:2]

array([[ 1,  2,  3],
       [ 4, 54,  6]])

In [48]:
# If we add another argument to the array, for example a[:2, 1:3], we get the first two rows but then the
# second and third column values only

a[:2,1:3]

array([[ 2,  3],
       [54,  6]])

In [49]:
# So, in multidimensional arrays, the first argument is for selecting rows, and the second argument is for 
# selecting columns

In [51]:
# It is important to realize that a slice of an array is a view into the same data. This is called passing by
# reference. So modifying the sub array will consequently modify the original array

# Here I'll change the element at position [0, 0], which is 2, to 50, then we can see that the value in the
# original array is changed to 50 as well

sub_array = a[:2,1:3]
print("Sub_array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("Sub_array index [0,0] value after change:", sub_array[0,0])
print("Orignal array index [0,1] value after change:", a[0,1])
print(sub_array)
print(a)

Sub_array index [0,0] value before change: 50
Sub_array index [0,0] value after change: 50
Orignal array index [0,1] value after change: 50
[[50  3]
 [54  6]]
[[ 1 50  3]
 [ 4 54  6]
 [ 6  7  8]]


## Trying Numpy with Data Sets

In [52]:
# Here we have a very popular dataset on wine quality, and we are going to only look at red wines. The data
# fields include: fixed acidity, volatile aciditycitric acid, residual sugar, chlorides, free sulfur dioxide,
# total sulfur dioxidedensity, pH, sulphates, alcohol, quality

In [53]:
# To load a dataset in Numpy, we can use the genfromtxt() function. We can specify data file name, delimiter
# (which is optional but often used), and number of rows to skip if we have a header row, hence it is 1 here

# The genfromtxt() function has a parameter called dtype for specifying data types of each column this
# parameter is optional. Without specifying the types, all types will be casted the same to the more
# general/precise type

wines = np.genfromtxt("C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/winequality-red.csv",
                     delimiter = ";", skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [54]:
# Recall that we can use integer indexing to get a certain column or a row. For example, if we want to select
# the fixed acidity column, which is the first coluumn, we can do so by entering the index into the array.
# Also remember that for multidimensional arrays, the first argument refers to the row, and the second
# argument refers to the column, and if we just give one argument then we'll get a single dimensional list
# back.

# So all rows combined but only the first column from them would be
print("one integer 0 for slicing: ", wines[:, 0])
# But if we wanted the same values but wanted to preserve that they sit in their own rows we would write
print("0 to 1 for slicing: \n", wines[:,0:1])

one integer 0 for slicing:  [7.4 7.8 7.8 ... 6.3 5.9 6. ]
0 to 1 for slicing: 
 [[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [55]:
# This is another great example of how the shape of the data is an abstraction which we can layer
# intentionally on top of the data we are working with.

In [56]:
# If we want a range of columns in order, say columns 0 through 3 (recall, this means first, second, and
# third, since we start at zero and don't include the training index value), we can do that too
wines[:, 0:3]

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]])

In [57]:
# What if we want several non-consecutive columns? We can place the indices of the columns that we want into
# an array and pass the array as the second argument. Here's an example

wines[:,[1,2,3]]

array([[0.7  , 0.   , 1.9  ],
       [0.88 , 0.   , 2.6  ],
       [0.76 , 0.04 , 2.3  ],
       ...,
       [0.51 , 0.13 , 2.3  ],
       [0.645, 0.12 , 2.   ],
       [0.31 , 0.47 , 3.6  ]])

In [58]:
# We can also do some basic summarization of this dataset. For example, if we want to find out the average
# quality of red wine, we can select the quality column. We could do this in a couple of ways, but the most
# appropriate is to use the -1 value for the index, as negative numbers mean slicing from the back of the
# list. We can then call the aggregation functions on this data.

wines[:,-1].mean()

5.6360225140712945

In [59]:
# Let's take a look at another dataset, this time on graduate school admissions. It has fields such as GRE
# score, TOEFL score, university rating, GPA, having research experience or not, and a chance of admission.
# With this dataset, we can do data manipulation and basic analysis to infer what conditions are associated
# with higher chance of admission. Let's take a look.

In [62]:
# We can specify data field names when using genfromtxt() to loads CSV data. Also, we can have numpy try and
# infer the type of a column by setting the dtype parameter to None

graduate_admission = np.genfromtxt('C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/Admission_Predict.csv',
                                   dtype = None, delimiter = ',',skip_header = 1,
                                   names = ('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [63]:
# Notice that the resulting array is actually a one-dimensional array with 400 tuples
graduate_admission.shape

(400,)

In [65]:
# We can retrieve a column from the array using the column's name for example, let's get the CGPA column and
# only the first five values.

graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [66]:
# Since the GPA in the dataset range from 1 to 10, and in the US it's more common to use a scale of up to 4,
# a common task might be to convert the GPA by dividing by 10 and then multiplying by 4

graduate_admission['CGPA'] = graduate_admission['CGPA']/10*4
graduate_admission['CGPA'][0:20]

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 , 3.36 , 3.6  , 3.64 , 3.2  , 3.28 , 3.32 , 3.48 , 3.2  ,
       3.52 , 3.4  ])

In [69]:
# Recall boolean masking. We can use this to find out how many students have had research experience by
# creating a boolean mask and passing it to the array indexing operator

print(len(graduate_admission[graduate_admission['Research']==1]))

219


In [73]:
# Since we have the data field chance of admission, which ranges from 0 to 1, we can try to see if students
# with high chance of admission (>0.8) on average have higher GRE score than those with lower chance of
# admission (<0.4)



# So first we use boolean masking to pull out only those students we are interested in based on their chance
# of admission, then we pull out only their GPA scores, then we print the mean values.

print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['GRE_Score'].mean())



328.7350427350427
302.2857142857143


In [74]:
# When we do the boolean masking we are left with an array with tuples in it still, and numpy holds underneath
# this a list of the columns we specified and their name and indexes.

graduate_admission[graduate_admission['Chance_of_Admit']>0.8]

array([(  1, 337, 118, 4, 4.5, 4.5, 3.86 , 1, 0.92),
       (  6, 330, 115, 5, 4.5, 3. , 3.736, 1, 0.9 ),
       ( 12, 327, 111, 4, 4. , 4.5, 3.6  , 1, 0.84),
       ( 23, 328, 116, 5, 5. , 5. , 3.8  , 1, 0.94),
       ( 24, 334, 119, 5, 5. , 4.5, 3.88 , 1, 0.95),
       ( 25, 336, 119, 5, 4. , 3.5, 3.92 , 1, 0.97),
       ( 26, 340, 120, 5, 4.5, 4.5, 3.84 , 1, 0.94),
       ( 33, 338, 118, 4, 3. , 4.5, 3.76 , 1, 0.91),
       ( 34, 340, 114, 5, 4. , 4. , 3.84 , 1, 0.9 ),
       ( 35, 331, 112, 5, 4. , 5. , 3.92 , 1, 0.94),
       ( 36, 320, 110, 5, 5. , 5. , 3.68 , 1, 0.88),
       ( 44, 332, 117, 4, 4.5, 4. , 3.64 , 0, 0.87),
       ( 45, 326, 113, 5, 4.5, 4. , 3.76 , 1, 0.91),
       ( 46, 322, 110, 5, 5. , 4. , 3.64 , 1, 0.88),
       ( 47, 329, 114, 5, 4. , 5. , 3.72 , 1, 0.86),
       ( 48, 339, 119, 5, 4.5, 4. , 3.88 , 0, 0.89),
       ( 49, 321, 110, 3, 3.5, 5. , 3.54 , 1, 0.82),
       ( 71, 332, 118, 5, 5. , 5. , 3.856, 1, 0.94),
       ( 72, 336, 112, 5, 5. , 5. , 3.904, 1, 

In [76]:
# Let's also do this with GPA
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['CGPA'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['CGPA'].mean())

3.7106666666666666
3.0222857142857142


In [77]:
# Hrm, well, I guess one could have expected this. The GPA and GRE for students who have a higher chance of
# being admitted, at least based on our cursory look here, seems to be higher.

# Regex

In [78]:
# First we'll import the re module, which is where python stores regular expression libraries.

import re

## re.search()

In [79]:
# There are several main processing functions in re that you might use. The first, match() checks for a match
# that is at the beginning of the string and returns a boolean. Similarly, search(), checks for a match
# anywhere in the string, and returns a boolean.

#lets create some text for an example
text = "This is a good day"

# now let's see it's a ood day or not:

if re.search("good",text):
    print("Wonderful")
else:
    print("Not wonderful")

Wonderful


## re.findall() and re.split()

In [95]:
# In addition to checking for conditionals, we can segment a string. The work that regex does here is called
# tokenizing, where the string is separated into substrings based on patterns. 

# The findall() and split() functions will parse the string for us and return chunks. Lets try and example
text = "Amy works diligently. Amy gets good grades.Our student Amy is succesful."

re.split("Amy", text)

['', ' works diligently. ', ' gets good grades.Our student ', ' is succesful.']

In [96]:
# You'll notice that split has returned an empty string, followed by a number of statements about Amy, all as
# elements of a list. If we wanted to count how many times we have talked about Amy, we could use findall()

re.findall("Amy",text)

['Amy', 'Amy', 'Amy']

In [97]:
# Ok, so we've seen that .search() looks for some pattern and returns a boolean, that .split() will use a
# pattern for creating a list of substrings, and that .findall() will look for a pattern and pull out all
# occurences.

In [98]:
# Now that we know how the python regex API works, lets talk about more complex patterns. The regex
# specification standard defines a markup language to describe patterns in text. Lets start with anchors.
# Anchors specify the start and/or the end of the string that you are trying to match. The caret character ^
# means start and the dollar sign character $ means end. If you put ^ before a string, it means that the text
# the regex processor retrieves must start with the string you specify. For ending, you have to put the $
# character after the string, it means that the text Regex retrieves must end with the string you specify.


# Here's an example
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

# Lets see if this begins with Amy
re.search("^Amy",text)


<re.Match object; span=(0, 3), match='Amy'>

In [99]:
# Notice that re.search() actually returned to us a new object, called re.Match object. An re.Match object
# always has a boolean value of True, as something was found, so you can always evaluate it in an if statement
# as we did earlier. The rendering of the match object also tells you what pattern was matched, in this case
# the word Amy, and the location the match was in, as the span.

## Patterns and character classes

In [100]:
# Let's talk more about patterns and start with character classes. Let's create a string of a single learners'
# grades over a semester in one course across all of their assignments

grades="ACAAAABCBCBAA"

# If we want to answer the question "How many B's were in the grade list?" we would just use B

re.findall("B",grades)

['B', 'B', 'B']

In [101]:
# If we wanted to count the number of A's or B's in the list, we can't use "AB" since this is used to match
# all A's followed immediately by a B. Instead, we put the characters A and B inside square brackets

re.findall("[AB]", grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']

In [102]:
# This is called the set operator. You can also include a range of characters, which are ordered
# alphanumerically. For instance, if we want to refer to all lower case letters we could use [a-z] Lets build
# a simple regex to parse out all instances where this student receive an A followed by a B or a C

re.findall("[A][B-C]",grades)

['AC', 'AB']

In [104]:
# Notice how the [AB] pattern describes a set of possible characters which could be either (A OR B), while the
# [A][B-C] pattern denoted two sets of characters which must have been matched back to back. You can write
# this pattern by using the pipe operator, which means OR

re.findall("AB|AC",grades)

['AC', 'AB']

In [105]:
# We can use the caret with the set operator to negate our results. For instance, if we want to parse out only
# the grades which were not A's

re.findall("^[^A]",grades)

[]

In [106]:
# It's an empty list, because the regex says that we want to match any value at the beginning of the string
# which is not an A. Our string though starts with an A, so there is no match found. And remember when you are
# using the set operator you are doing character-based matching. So you are matching individual characters in
# an OR method.

## Quantifiers

In [107]:
# Ok, so we've talked about anchors and matching to the beginning and end of patterns. And we've talked about
# characters and using sets with the [] notation. We've also talked about character negation, and how the pipe
# | character allows us to or operations. Lets move on to quantifiers.

In [108]:
# Quantifiers are the number of times you want a pattern to be matched in order to match. The most basic
# quantifier is expressed as e{m,n}, where e is the expression or character we are matching, m is the minimum
# number of times you want it to matched, and n is the maximum number of times the item could be matched.

# Let's use these grades as an example. How many times has this student been on a back-to-back A's streak?

re.findall("A{2,10}",grades)

['AAAA', 'AA']

In [109]:
# So we see that there were two streaks, one where the student had four A's, and one where they had only two
# A's

# We might try and do this using single values and just repeating the pattern

re.findall("A{1,1}A{1,1}",grades)

['AA', 'AA', 'AA']

In [110]:
# As you can see, this is different than the first example. The first pattern is looking for any combination
# of two A's up to ten A's in a row. So it sees four A's as a single streak. The second pattern is looking for
# two A's back to back, so it sees two A's followed immediately by two more A's. We say that the regex
# processor begins at the start of the string and consumes variables which match patterns as it does.

# It's important to note that the regex quantifier syntax does not allow you to deviate from the {m,n}
# pattern. In particular, if you have an extra space in between the braces you'll get an empty result

re.findall("A{2, 2}", grades)

[]

In [111]:
# And as we have already seen, if we don't include a quantifier then the default is {1,1}

re.findall("AA",grades)

['AA', 'AA', 'AA']

In [112]:
# and if you just have one number in the braces, it's considered to be both m and n

re.findall("A{2}", grades)

['AA', 'AA', 'AA']

In [113]:
# Using this, we could find a decreasing trend in a student's grades

re.findall("A{1,10}B{1,10}C{1,10}",grades)

['AAAABC']

In [114]:
# Now, that's a bit of a hack, because we included a maximum that was just arbitrarily large. There are three
# other quantifiers that are used as short hand, an asterix * to match 0 or more times, a question mark ? to
# match one or more times, or a + plus sign to match one or more times. Lets look at a more complex example,
# and load some data scraped from wikipedia

In [154]:
with open('C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/ferpa.txt',
          'r') as file:
    wiki = file.read()
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [120]:
# Scanning through this document one of the things we notice is that the headers all have the words [edit]
# behind them, followed by a newline character. So if we wanted to get a list of all of the headers in this
# article we could do so using re.findall. Here we are using {1,100} to match from 1 to 100 times.

re.findall("[a-zA-Z]{1,100}\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [121]:
# Ok, that didn't quite work. It got all of the headers, but only the last word of the header, and it really
# was quite clunky. Lets iteratively improve this. First, we can use \w to match any letter, including digits
# and numbers.

re.findall("[\w]*\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [123]:
# Now that we have shortened the regex, let's improve it a little bit. We can add in a spaces using the space
# character

re.findall("[\w ]*\[edit\]",wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [125]:
# Ok, so this gets us the list of section titles in the wikipedia page! You can now create a list of titles by
# iterating through this and applying another regex

for title in re.findall("[\w ]*\[edit\]", wiki):
# Now we will take that intermediate result and split on the square bracket [ just taking the first result
  print(re.split("[\[]",title)[0])


Overview
Access to public records
Student medical records


## Groups

In [126]:
# Ok, this works, but it's a bit of a pain. To this point we have been talking about a regex as a single
# pattern which is matched. But, you can actually match different patterns, called groups, at the same time,
# and then refer to the groups you want. To group patterns together you use parentheses, which is actually
# pretty natural. Lets rewrite our findall using groups

re.findall("([\w ]*)(\[edit\])",wiki)

[('Overview', '[edit]'),
 ('Access to public records', '[edit]'),
 ('Student medical records', '[edit]')]

## re.finditer()

In [131]:
# Nice - we see that the python re module breaks out the result by group. We can actually refer to groups by
# number as well with the match objects that are returned. But, how do we get back a list of match objects?
# Thus far we've seen that findall() returns strings, and search() and match() return individual Match
# objects. But what do we do if we want a list of Match objects? In this case, we use the function finditer()

for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.groups())

('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')


In [135]:
# We see here that the groups() method returns a tuple of the group. We can get an individual group using
# group(number), where group(0) is the whole match, and each other number is the portion of the match we are
# interested in. In this case, we want group(1)

for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.group(1))

Overview
Access to public records
Student medical records


In [138]:
# One more piece to regex groups that I rarely use but is a good idea is labeling or naming groups. In the
# previous example I showed you how you can use the position of the group. But giving them a label and looking
# at the results as a dictionary is pretty useful. For that we use the syntax (?P<name>), where the parethesis
# starts the group, the ?P indicates that this is an extension to basic regexes, and <name> is the dictionary
# key we want to use wrapped in <>.

for item in re.finditer("(?P<title>[\w ]*)(?P<edit_link>\[edit\])",wiki):
    print(item.groupdict()['title'])
    print(item.groupdict()['edit_link'])

Overview
[edit]
Access to public records
[edit]
Student medical records
[edit]


In [140]:
# Of course, we can print out the whole dictionary for the item too, and see that the [edit] string is still
# in there. Here's the dictionary kept for the last match

print(item.groupdict())

{'title': 'Student medical records', 'edit_link': '[edit]'}


In [141]:
# Ok, we have seen how we can match individual character patterns with [], how we can group matches together
# using (), and how we can use quantifiers such as *, ?, or m{n} to describe patterns. Something I glossed
# over in the previous example was the \w, which standards for any word character. There are a number of
# short hands which are used with regexes for different kinds of characters, including:
# a . for any single character which is not a newline
# a \d for any digit
# and \s for any whitespace character, like spaces and tabs

## Look-ahead and Look-behind

In [143]:
# One more concept to be familiar with is called "look ahead" and "look behind" matching. In this case, the
# pattern being given to the regex engine is for text either before or after the text we are trying to
# isolate. For example, in our headers we want to isolate text which  comes before the [edit] rendering, but
# we actually don't care about the [edit] text itself. Thus far we have been throwing the [edit] away, but if
# we want to use them to match but don't want to capture them we could put them in a group and use look ahead
# instead with ?= syntax

#(?=...) is a positive lookahead assertion. It matches if there is the part in parentheses after ?= matches at the current position, but it will not consume any characters for the match. 
#E.g. the regex a(?=b) will match an a followed by a b, but won't return the b as part of the match.

In [155]:
for item in re.finditer("(?P<title>[\w ]+)(?=\[edit\])",wiki):
    # What this regex says is match two groups, the first will be named and called title, will have any amount
    # of whitespace or regular word characters, the second will be the characters [edit] but we don't actually
    # want this edit put in our output match objects
    print(item)
    

<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


## Example : Wikipedia Data

In [156]:
# Let's look at some more wikipedia data. Here's some data on universities in the US which are buddhist-based
with open("C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/buddhist.txt",encoding="utf8") as file:
    # we'll read that into a variable called wiki
    wiki=file.read()
# and lets print that variable out to the screen
wiki

'Buddhist universities and colleges in the United States\nFrom Wikipedia, the free encyclopedia\nJump to navigationJump to search\n\nThis article needs additional citations for verification. Please help improve this article by adding citations to reliable sources. Unsourced material may be challenged and removed.\nFind sources: "Buddhist universities and colleges in the United States" – news · newspapers · books · scholar · JSTOR (December 2009) (Learn how and when to remove this template message)\nThere are several Buddhist universities in the United States. Some of these have existed for decades and are accredited. Others are relatively new and are either in the process of being accredited or else have no formal accreditation. The list includes:\n\nDhammakaya Open University – located in Azusa, California, part of the Thai Wat Phra Dhammakaya[1]\nDharmakirti College – located in Tucson, Arizona Now called Awam Tibetan Buddhist Institute (http://awaminstitute.org/)\nDharma Realm Buddh

In [159]:
# We can see that each university follows a fairly similar pattern, with the name followed by an – then the
# words "located in" followed by the city and state

# I'll actually use this example to show you the verbose mode of python regexes. The verbose mode allows you
# to write multi-line regexes and increases readability. For this mode, we have to explicitly indicate all
# whitespace characters, either by prepending them with a \ or by using the \s special value. However, this
# means we can write our regex a bit more like code, and can even include comments with #
pattern="""
(?P<title>.*)        #the university title
(–\ located\ in\ )   #an indicator of the location
(?P<city>\w*)        #city the university is in
(,\ )                #separator for the state
(?P<state>\w*)       #the state the city is located in"""

# Now when we call finditer() we just pass the re.VERBOSE flag as the last parameter, this makes it much
# easier to understand large regexes!
for item in re.finditer(pattern,wiki,re.VERBOSE):
    # We can get the dictionary returned for the item with .groupdict()
    print(item.groupdict())

{'title': 'Dhammakaya Open University ', 'city': 'Azusa', 'state': 'California'}
{'title': 'Dharmakirti College ', 'city': 'Tucson', 'state': 'Arizona'}
{'title': 'Dharma Realm Buddhist University ', 'city': 'Ukiah', 'state': 'California'}
{'title': 'Ewam Buddhist Institute ', 'city': 'Arlee', 'state': 'Montana'}
{'title': 'Institute of Buddhist Studies ', 'city': 'Berkeley', 'state': 'California'}
{'title': 'Maitripa College ', 'city': 'Portland', 'state': 'Oregon'}
{'title': 'University of the West ', 'city': 'Rosemead', 'state': 'California'}
{'title': 'Won Institute of Graduate Studies ', 'city': 'Glenside', 'state': 'Pennsylvania'}


In [166]:
with open("C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/nytimeshealth.txt",encoding="utf8") as file:
    health = file.read()
health


'548662191340421120|Sat Dec 27 02:10:34 +0000 2014|Risks in Using Social Media to Spot Signs of Mental Distress http://nyti.ms/1rqi9I1\n548579831169163265|Fri Dec 26 20:43:18 +0000 2014|RT @paula_span: The most effective nationwide diabetes prevention program you\'ve probably never heard of:  http://newoldage.blogs.nytimes.com/2014/12/26/diabetes-prevention-that-works/\n548579045269852161|Fri Dec 26 20:40:11 +0000 2014|The New Old Age Blog: Diabetes Prevention That Works http://nyti.ms/1xm7fTi\n548444679529041920|Fri Dec 26 11:46:15 +0000 2014|Well: Comfort Casseroles for Winter Dinners http://nyti.ms/1xTNoO0\n548311901227474944|Fri Dec 26 02:58:39 +0000 2014|High-Level Knowledge Before Veterans Affairs Scandal http://nyti.ms/13yCpvS\n548305625449787392|Fri Dec 26 02:33:42 +0000 2014|Your Money: Affordable Care Act’s Tax Effects Now Loom for Filers http://nyti.ms/13yAtUf\n548283182853160960|Fri Dec 26 01:04:32 +0000 2014|Well: Christmas in the Hospital http://nyti.ms/1vtPNcm\n548278414

In [167]:
# So here we can see there are tweets with fields separated by pipes |. Lets try and get a list of all of the
# hashtags that are included in this data. A hashtag begins with a pound sign (or hash mark) and continues
# until some whitespace is found

# So lets create a pattern. We want to include the hash sign first, then any number of alphanumeric
# characters. And we end when we see some whitespace

pattern = '#[\w\d]*(?=\s)'

# Notice that the ending is a look ahead. We're not actually interested in matching whitespace in the return
# value. Also notice that I use an asterix * instead of the plus + for the matching of alphabetical characters
# or digits, because a + would require at least one of each

# Lets searchg and display all of the hashtags

re.findall(pattern, health)

['#askwell',
 '#pregnancy',
 '#Colorado',
 '#VegetarianThanksgiving',
 '#FallPrevention',
 '#Ebola',
 '#Ebola',
 '#ebola',
 '#Ebola',
 '#Ebola',
 '#EbolaHysteria',
 '#AskNYT',
 '#Ebola',
 '#Ebola',
 '#Liberia',
 '#Excalibur',
 '#ebola',
 '#Ebola',
 '#dallas',
 '#nobelprize2014',
 '#ebola',
 '#ebola',
 '#monrovia',
 '#ebola',
 '#nobelprize2014',
 '#ebola',
 '#nobelprize2014',
 '#Medicine',
 '#Ebola',
 '#Monrovia',
 '#Ebola',
 '#smell',
 '#Ebola',
 '#Ebola',
 '#Ebola',
 '#Monrovia',
 '#Ebola',
 '#ebola',
 '#monrovia',
 '#liberia',
 '#benzos',
 '#ClimateChange',
 '#Whole',
 '#Wheat',
 '#Focaccia',
 '#Tomatoes',
 '#Olives',
 '#Recipes',
 '#Health',
 '#Ebola',
 '#Monrovia',
 '#Liberia',
 '#Ebola',
 '#Ebola',
 '#Liberia',
 '#Ebola',
 '#blood',
 '#Ebola',
 '#organtrafficking',
 '#EbolaOutbreak',
 '#SierraLeone',
 '#Freetown',
 '#SierraLeone',
 '#ebolaoutbreak',
 '#kenema',
 '#ebola',
 '#Ebola',
 '#ebola',
 '#ebola',
 '#Ebola',
 '#ASMR',
 '#AIDS2014',
 '#AIDS',
 '#MH17',
 '#benzos']

In [169]:
# We can see here that there were lots of ebola related tweeks in this particular dataset.

In [170]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [172]:
a = np.random.rand(20,20)

In [173]:
b = np.random.rand(20,20)

In [174]:
l2_dist(a.T,b.T)

7.794572505162328

In [175]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

7.794572505162328

In [176]:
c = np.reshape(a, (20 * 20))

In [178]:
c.shape

(400,)

In [189]:
np.arange(1,4,1).ndim()==1

TypeError: 'int' object is not callable

In [183]:
np.array([1,2,3,4]).shape

(4,)

In [187]:
np.random.rand(4).shape

(4,)

In [185]:
np.random.rand(4,1)

array([[0.48198134],
       [0.16300076],
       [0.08074816],
       [0.36769954]])

In [188]:
np.linspace(1,4,4).shape

(4,)

In [190]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [194]:
import re 
s = 'ACBCAC'

re.findall('^AC', s)

['AC']

In [195]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

In [197]:
L

5

In [224]:
a = 'http://www.baidu.com'

In [225]:
re.findall("(?<=https:\/\/)([A-Za-z0-9.]*)",a)

[]

In [218]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4


In [260]:
import re
def grades():
    with open ("C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/grades.txt", "r") as file:
        grades = file.read()
    
    # YOUR CODE HERE
    return re.findall('([\w]*\S+ [\w]*\S+): B',grades)
    #gradeB = []
    #for item in re.finditer('([\w]*\S+ [\w]*\S+): B',grades):
    #    gradeB.append(item.group("name"))
    #return gradeB
    #raise NotImplementedError()

In [261]:
grades()

['Bell Kassulke',
 'Simon Loidl',
 'Elias Jovanovic',
 'Hakim Botros',
 'Emilie Lorentsen',
 'Jake Wood',
 'Fatemeh Akhtar',
 'Kim Weston',
 'Yasmin Dar',
 'Viswamitra Upandhye',
 'Killian Kaufman',
 'Elwood Page',
 'Elodie Booker',
 'Adnan Chen',
 'Hank Spinka',
 'Hannah Bayer']

In [402]:
with open ("C:/Users/tkhan050/Documents/Blogs/Study Materials/Introduction to Data Science in Python/logdata.txt", "r") as file:
        logdata = file.read()
logdata    

'146.204.224.152 - feest6811 [21/Jun/2019:15:45:24 -0700] "POST /incentivize HTTP/1.1" 302 4622\n197.109.77.178 - kertzmann3129 [21/Jun/2019:15:45:25 -0700] "DELETE /virtual/solutions/target/web+services HTTP/2.0" 203 26554\n156.127.178.177 - okuneva5222 [21/Jun/2019:15:45:27 -0700] "DELETE /interactive/transparent/niches/revolutionize HTTP/1.1" 416 14701\n100.32.205.59 - ortiz8891 [21/Jun/2019:15:45:28 -0700] "PATCH /architectures HTTP/1.0" 204 6048\n168.95.156.240 - stark2413 [21/Jun/2019:15:45:31 -0700] "GET /engage HTTP/2.0" 201 9645\n71.172.239.195 - dooley1853 [21/Jun/2019:15:45:32 -0700] "PUT /cutting-edge HTTP/2.0" 406 24498\n180.95.121.94 - mohr6893 [21/Jun/2019:15:45:34 -0700] "PATCH /extensible/reinvent HTTP/1.1" 201 27330\n144.23.247.108 - auer7552 [21/Jun/2019:15:45:35 -0700] "POST /extensible/infrastructures/one-to-one/enterprise HTTP/1.1" 100 22921\n2.179.103.97 - lind8584 [21/Jun/2019:15:45:36 -0700] "POST /grow/front-end/e-commerce/robust HTTP/2.0" 304 14641\n241.114.1

In [394]:
pattern="""
(?P<host>\d+[.]\d+[.]\d+[.]\d+)
(\s-\s)
(?P<user_name>[a-z-]\S*)
(\s\[)
(?P<time>\d*\/\w*\/\d*\:\d*\d*\:\d*\:\d*\s[-]\d*)
(\]\s\")
(?P<request>[A-Z]*\s\/[a-z]*\s[A-Z]*\/\d*[.]\d*)
"""

for item in re.finditer(pattern,logdata, re.VERBOSE):
    print(item.groupdict())

{'host': '146.204.224.152', 'user_name': 'feest6811', 'time': '21/Jun/2019:15:45:24 -0700', 'request': 'POST /incentivize HTTP/1.1'}
{'host': '100.32.205.59', 'user_name': 'ortiz8891', 'time': '21/Jun/2019:15:45:28 -0700', 'request': 'PATCH /architectures HTTP/1.0'}
{'host': '168.95.156.240', 'user_name': 'stark2413', 'time': '21/Jun/2019:15:45:31 -0700', 'request': 'GET /engage HTTP/2.0'}
{'host': '159.252.184.44', 'user_name': 'fay7852', 'time': '21/Jun/2019:15:45:54 -0700', 'request': 'GET /convergence HTTP/2.0'}
{'host': '40.167.172.66', 'user_name': 'kshlerin3090', 'time': '21/Jun/2019:15:45:57 -0700', 'request': 'HEAD /convergence HTTP/2.0'}
{'host': '115.214.173.248', 'user_name': 'hauck8214', 'time': '21/Jun/2019:15:46:00 -0700', 'request': 'PUT /optimize HTTP/1.1'}
{'host': '62.79.96.179', 'user_name': 'mayer1069', 'time': '21/Jun/2019:15:46:15 -0700', 'request': 'HEAD /facilitate HTTP/1.0'}
{'host': '63.208.115.205', 'user_name': '-', 'time': '21/Jun/2019:15:46:19 -0700', 're

In [404]:
req = re.findall('(\d+[.]\d+[.]\d+[.]\d+) - ([a-z-]\S*) [\[](\S+ -0700)\] "([A-Z]\S+ \/\S+ HTTP\/[0-9.]+)',logdata)

In [405]:
req

[('146.204.224.152',
  'feest6811',
  '21/Jun/2019:15:45:24 -0700',
  'POST /incentivize HTTP/1.1'),
 ('197.109.77.178',
  'kertzmann3129',
  '21/Jun/2019:15:45:25 -0700',
  'DELETE /virtual/solutions/target/web+services HTTP/2.0'),
 ('156.127.178.177',
  'okuneva5222',
  '21/Jun/2019:15:45:27 -0700',
  'DELETE /interactive/transparent/niches/revolutionize HTTP/1.1'),
 ('100.32.205.59',
  'ortiz8891',
  '21/Jun/2019:15:45:28 -0700',
  'PATCH /architectures HTTP/1.0'),
 ('168.95.156.240',
  'stark2413',
  '21/Jun/2019:15:45:31 -0700',
  'GET /engage HTTP/2.0'),
 ('71.172.239.195',
  'dooley1853',
  '21/Jun/2019:15:45:32 -0700',
  'PUT /cutting-edge HTTP/2.0'),
 ('180.95.121.94',
  'mohr6893',
  '21/Jun/2019:15:45:34 -0700',
  'PATCH /extensible/reinvent HTTP/1.1'),
 ('144.23.247.108',
  'auer7552',
  '21/Jun/2019:15:45:35 -0700',
  'POST /extensible/infrastructures/one-to-one/enterprise HTTP/1.1'),
 ('2.179.103.97',
  'lind8584',
  '21/Jun/2019:15:45:36 -0700',
  'POST /grow/front-end/e